# Generated by Django 6.0.4 on 2026-05-10 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('child_age', models.CharField(help_text='e.g., 3 years old', max_length=20)),
                ('message', models.TextField()),
                ('preferred_visit_date', models.DateField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=50)),
                ('child_last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('desired_start_date', models.DateField()),
                ('special_needs', models.TextField(blank=True, help_text='Any allergies, medical conditions, or learning needs')),
                ('how_did_you_hear', models.CharField(blank=True, choices=[('google', 'Google Search'), ('facebook', 'Facebook'), ('friend', 'Friend/Family'), ('flyer', 'Flyer/Brochure'), ('other', 'Other')], max_length=100)),
                ('birth_certificate', models.FileField(upload_to='applications/birth_certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('immunization_record', models.FileField(blank=True, upload_to='applications/immunization/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('parent_id', models.FileField(blank=True, upload_to='applications/parent_ids/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('waitlist', 'On Waitlist'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, help_text='Auto-calculated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('program_applied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schools.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admissions.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
