# Generated by Django 6.0.4 on 2026-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(choices=[('classroom', 'Classroom'), ('playground', 'Playground'), ('safety', 'Safety Feature'), ('medical', 'Medical Facility'), ('transport', 'Transport')], max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('baby', 'Baby Class (1.5-2.5 yrs)'), ('pp1', 'PP1 (3-4 yrs)'), ('pp2', 'PP2 (4-5 yrs)'), ('daycare', 'Daycare'), ('afterschool', 'After School Program')], max_length=50, unique=True)),
                ('description', models.TextField(help_text='What children learn in this class')),
                ('age_range', models.CharField(help_text='e.g., 3-4 years', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on website')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text="e.g., {'monday': '9am-12pm'}")),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g., Head Teacher, PP1 Lead', max_length=100)),
                ('bio', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('qualifications', models.TextField(blank=True, help_text='Comma-separated: B.Ed, Montessori Certified, etc.')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='schools.program')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
